# 服务器端口设置
server:
  port: 8080
  # 指定session超时时间为2小时
  servlet:
    session:
      timeout: PT2H

# 四大件和数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Sys0626.
    type: com.alibaba.druid.pool.DruidDataSource
  # redis相关
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
# mybatis相关
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true

# 分页插件
pagehelper:
  # 方言
  helper-dialect: mysql
  # 分页合理化
  reasonable: true
  support-methods-arguments: true

